replicaCount: 1

image:
  repository: quay.io/app_conn_workshop/travels-demo-ui
  pullPolicy: IfNotPresent
  tag: latest

podSecurityContext: {}


securityContext: {}

service:
  type: ClusterIP
  port: 8080

resources: {}


api:
  allcities:
  city:
  keyvalue: blue
  keyname: APIKEY