replicaCount: 1

image:
  repository: quay.io/app_conn_workshop/travels-demo-ui
  pullPolicy: IfNotPresent
  tag: latest

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources: {}

httpRoute:
  hostName:

api:
  keyvalue: blue
  keyname: APIKEY