---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ include "kiali-operator.name" . }}-operator
  namespace: openshift-operators
  annotations:
    {{- include "kiali-operator.argocd-syncwave" . | nindent 4 }}
spec:
  channel: {{ .Values.subscription.channel }}
  installPlanApproval: {{ .Values.subscription.installPlanApproval }}
  name: {{ .Values.subscription.name }}
  source: {{ .Values.subscription.source }}
  sourceNamespace: {{ .Values.subscription.sourceNamespace }}
