replicaCount: 1

image:
  repository: quay.io/redhat-servicemesh-apim-demo/travels-demo-ui
  pullPolicy: IfNotPresent
  tag: final

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources: {}

httpRoute:
  gateway:
    name:
    namespace: 
  hostName:


deployDb: false