namespace: "webterminal"

webterminal:
  subscription:
    channel: "fast"
    installPlanApproval: Automatic
    name: web-terminal
    source: redhat-operators
    sourceNamespace: openshift-marketplace

argocd:
  enabled: true
  operatorgroup:
    syncwave: "-3"
  operator:
    syncwave: "-2"
