apiVersion: v1
kind: Secret
metadata:
  name: wasm-plugin-pull-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: -1
type: Opaque
data:
  docker-username: {{ Values.registry.username }}
  docker-password: {{ Values.registry.password }}

