apiVersion: route.openshift.io/v1
kind: Route
name: tracing-ui
namespace: tracing-system
resource_definition:
  spec:
    port:
      targetPort: jaeger-ui
    to:
      kind: Service
      name: tempo-sample-query-frontend