---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: "{{ include "keycloak.name" . }}-operatorgroup"
  namespace: {{ include "keycloak.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  targetNamespaces:
    - {{ include "keycloak.namespace" . }}
