kind: Istio
apiVersion: sailoperator.io/v1
metadata:
  name: {{ include "istio.name" . }}
  namespace: istio-system
spec:
  version: {{ .Values.istio.version }}
  namespace: istio-system
  updateStrategy:
    type: InPlace

  # Disable autoscaling to reduce dev resources
  values:
    pilot:
      autoscaleEnabled: false
    meshConfig:
      extensionProviders:
      - name: otel
        opentelemetry:
          port: 4317
          service: otel-collector.opentelemetrycollector.svc.cluster.local