kind: Deployment
apiVersion: apps/v1
metadata:
  name: travels-demo-ui
  namespace: blue-portal
  labels:
    app: travels-demo-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travels-demo-ui
  template:
    metadata:
      labels:
        app: travels-demo-ui
        deploymentconfig: travels-demo-ui
    spec:
      containers:
        - name: travels-demo-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: NODE_ENV
              value: prod
            - name: PORT
              value: '8080'
            - name: WHOAMI
              value: blue
            - name: API_GET_CITIES
              value: YOUR_API_URL
            - name: API_GET_DETAILS_FOR_CITY
              value: YOUR_API_URL
            - name: API_USER_KEY_NAME
              value: YOUR_API_KEY_NAME
            - name: API_USER_KEY_VALUE
              value: YOUR_API_KEY_VALUE
          imagePullPolicy: IfNotPresent
